server:
  port: 8081

spring:
  main:
    banner-mode: off
#  thymeleaf:
#    suffix: .html
#    prefix: classpath:/templates/
#    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbms?ssl=false&characterEccodeing=utf8
    username: root
    password: 123456

#mybatis:
#  mapper-locations: classpath:/mapper/**.xml
#  type-aliases-package: com.lc.pojo

